# apiVersion: storage.k8s.io/v1
# kind: StorageClass
# metadata:
#   name: demo-storage
# provisioner: ebs.csi.aws.com
# volumeBindingMode: Immediate
# parameters:
#   type: gp2
#   fsType: ext4
# reclaimPolicy: Delete
