---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZG13YjUzb2Qy
  CLOUDINARY_KEY: MTc0NTU3MTE2MzcyMjU1
  CLOUDINARY_SECRET: YXVHc1RsRXlEaEpmVHNDQU1JQjB6YWsxbWFF
  MAPBOX_TOKEN: c2suZXlKMUlqb2liV0Z1YjJvek1EQXpJaXdpWVNJNkltTnRNR3BoYUdKNllqQTBkMmd5YTNCcWFUUmlZak00ZDJFaWZRLm9vWXBiUC1FOC04UlQ4QmlYVVNja0E=
  DB_URL: bW9uZ29kYitzcnY6Ly92YXJtYXBvdHRodXJpNDpWYXJtYV8zMDAzQGNsdXN0ZXIwLmVheWpjLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==
  SECRET: ZGV2b3Bzc2hhY2s=